import { chromium } from "playwright-core";
const url = process.argv[2] || "http://127.0.0.1:5179/";
const out = process.argv[3] || "shots";
const exe = process.argv[4] || "/usr/bin/google-chrome";
const b = await chromium.launch({ executablePath: exe, args: ["--no-sandbox"] });
const settle = async (p) => { await p.waitForLoadState("networkidle").catch(() => {}); await p.evaluate(() => document.fonts.ready); await p.waitForTimeout(1200); };
let p = await b.newPage({ viewport: { width: 1440, height: 900 } });
await p.goto(url); await settle(p);
await p.screenshot({ path: `${out}/desktop-hero.png` });
await p.evaluate(() => document.querySelector("#work").scrollIntoView({ behavior: "instant" })); await p.waitForTimeout(1500);
await p.screenshot({ path: `${out}/desktop-work.png` });
if (process.argv[5] === "full") await p.screenshot({ path: `${out}/desktop-full.png`, fullPage: true });
const m = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
await m.goto(url); await settle(m);
await m.screenshot({ path: `${out}/mobile-hero.png` });
if (process.argv[5] === "full") await m.screenshot({ path: `${out}/mobile-full.png`, fullPage: true });
await m.evaluate(() => window.scrollTo(0, 0));
await m.click(".burger"); await m.waitForTimeout(1100);
await m.screenshot({ path: `${out}/mobile-menu.png` });
const ov = await m.evaluate(() => document.documentElement.scrollWidth - window.innerWidth);
console.log("mobile overflow px:", ov);
await b.close();
